sudo: required

services:
  - docker

script:
  - docker build -t cordi .
  - docker run cordi /bin/sh -c "cordova telemetry on && cordova create test && cd test && cordova platform add android && cordova build android"
